version: '3.7'
services:
  docker-nmap:
    hostname: docker-nmap
    build:
      context: ./nmap
      dockerfile: Dockerfile
    image: docker-nmap
    restart: "no"
    networks:
      - splunk
    container_name: docker-nmap
    depends_on:
      - "docker-splunk"
  docker-mysql:
    hostname: docker-mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: docker-mysql
    ports:
      - "3306:3306"
    restart: "no"
    networks:
      - splunk
    volumes:
      - var_log_mysql:/var/log/mysql
    container_name: docker-mysql
  docker-splunk:
    hostname: docker-splunk
    build:
      context: ./splunk
      dockerfile: Dockerfile
    image: docker-splunk
#    environment:
#      - SPLUNK_ENABLE_LISTEN=9997
#      - SPLUNK_START_ARGS=--accept-license --no-prompt --answer-yes
#      - SPLUNK_USERNAME=admin
#      - SPLUNK_PASSWORD=password
    restart: always
    networks:
      - splunk
    volumes:
      - opt_splunk_etc:/opt/splunk/etc
      - opt_splunk_var:/opt/splunk/var
      - var_log_mysql:/var/log/mysql
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
      - "514:514/udp"
    depends_on:
      - "docker-mysql"
    restart: always
    container_name: docker-splunk
volumes:
  opt_splunk_etc:
  opt_splunk_var:
  var_log_mysql:
networks:
  splunk:
